# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b06d887d82db8bc7a80517e6ac9f47818c50854e40cb01024b5b9bd939b7a03bd8f4b0412f86313ffaddc516ec708288046c0e4bd8e190ca74265fe1864d32b8

test:
  secret_key_base: e07c9adb4bd98bc1bda3972295e96d6b984ea7591d04a208f5e1496e1b926bf34bbda34cca0beb04d65e371fb4069197e0c707f707e516a50cd6f81520145dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
